### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Protowise** [PixelExperience/official_devices#2228] opened 2021-05-01 10:21 UTC
## Device you want to apply for
```
OnePlus 5/5T (cheeseburger/dumpling)
```

## Device tree sources

```
https://github.com/Protowise/device_oneplus_msm8998-common
https://github.com/Protowise/device_oneplus_cheeseburger
https://github.com/Protowise/device_oneplus_dumpling
https://github.com/Protowise/kernel_oneplus_msm8998
https://github.com/Protowise/vendor_oneplus
```

## Number of ROM's you maintain officially
```
0
```

## Any Exceptions/special concern?
```
No
```

### Telegram username
```
http://t.me/protocheese
```

### GitHub username
```
Protowise
```

**Comment by Maitreya29** [comment] 2021-05-01 11:18
Just saw this and couldn't help myself but say this, do not  give this guy official. Previously his trees had absolutely ZERO authorship and now 50% commits still don't. He has a bunch of things which are not fixed including but not limited to Hotword enrollment. If I recall correctly this guy never even released a single build. There is another builder @xlexip who has been doing unofficial since months now with better trees that respect authorship and a much stable build. He also knows how to do things and cares about users. Just my two cents the decision is upto the team.

**Comment by xLexip** [comment] 2021-05-01 11:39
Heyo.
I can confirm Maitreya descriptions. I particularly want to refer to the overlays and device settings (among other things).
In addition, there actually are device-specific "special concerns", especially because important functionality commits are missing. However, this should be noticed in a test...

**Comment by KakatkarAkshay** [comment] 2021-05-01 11:43
Review is as follows.

You are setting Custom Build Fingerprint which is not allowed.
Your commits do not have proper authorship or commit messages.

Sorry to say that your application was not accepted

**Closed as completed by KakatkarAkshay** 2021-05-01 11:43 UTC
Labels: validated
