### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by subhadipjana866** [PixelExperience/official_devices#3224] opened 2023-12-09 10:43 UTC
### Device you want to apply for

Redmi Note 9 (merlinx)

### Device Tree Sources

Device tree for merlinx : https://github.com/subhadipjana866/device_xiaomi_merlinx
Device tree for mt6768(common device tree to inherit) : https://github.com/subhadipjana866/device_xiaomi_mt6768-common
Vendor tree : https://github.com/subhadipjana866/device_xiaomi_mt6768_vendor

### Number of ROM's you maintain officially

0

### Any Exceptions/special concern?

I need a server (Compute Engine) to build pixel experience custom rom.

### Telegram username

Ryuk866

### GitHub username

 subhadipjana866

**Comment by RisenID** [comment] 2023-12-09 10:45
Duplicate of #3223

**Closed as completed** 2023-12-09 10:45 UTC
